pipeline {
    agent any

    stages {

        stage('Run Tests') {
            steps {
                dir('jenkins-selenium-demo') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            junit 'jenkins-selenium-demo/target/surefire-reports/*.xml'
        }
    }
}